### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Gogiu23** [necesito-un-trastero/id-doc-validator#15]
Hey well done. Why don't try/catch for error handling in your codee. Is better and more efficient than return value. Great job anyway

**Comment by ogonzi** [comment]
Hey @Gogiu23! How nice to have you here 😄 . I did throw errors before but I changed it to return false since I find that throwing errors is more suited for critical errors that interrupt the flow of a program. If someone uses the validator wrongly, since it will never be a critical error, I prefer that it returns false and not to interrupt their program (assuming they don't use a try-catch, which you usually never do for a validator)
